var React = require('react');
var ReactDOM = require('react-dom');
var ReactFartscroll = require('react-fartscroll');

var App = React.createClass({
	render () {
		return (
			<div>
				<ReactFartscroll />
					<ul>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	            <li>Testing.</li>
	        </ul>																																			
			</div>
		);
	}
});

ReactDOM.render(<App />, document.getElementById('app'));
